### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/rma#123]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Dependencies

https://github.com/OCA/crm/issues/179

- [x] crm_claim
- [ ] crm_claim_code

# Modules to migrate

- [x] product_warranty + #137 - By @osi-scampbell - in #139 
- [ ] crm_claim_categ_as_name
- [ ] crm_claim_ext
- [ ] crm_claim_rma
- [ ] crm_claim_rma_code - By @larmar - #129 
- [ ] crm_rma_advance_location
- [ ] crm_rma_by_shop
- [ ] crm_rma_location - By @pragyachhabra - #130
- [ ] crm_rma_lot_mass_return
- [ ] crm_rma_stock_location

**Comment by emagdalenaC2i** [comment]
@pedrobaeza There is a PR for the migration of crm_rma_location - By @pragyachhabra - #130 

There is a PR for the migration of crm_claim_rma - By @max3903  - #128

**Comment by emagdalenaC2i** [comment]
@pedrobaeza the PR #128 is for v10.0 sorry, my fault
