### ISSUE TITLE
[MIG] product_warranty 11.0.1.0.0

### ISSUE THREAD

**Issue by max3903** [OCA/rma#137]
Hello,

Did I miss something or there is no more product warranty field on the product template in version 11?

Thanks

# Todo
- [x] Migrate product_warranty to version 11
- [x] Add a float field "Warranty" (warranty) on the product template
- [x] Add a selection field "Warranty Type" (warranty_type) on the product template with: Day(s), Week(s), Month(s), Year(s)

**Comment by rousseldenis** [comment]
Yes !
https://github.com/odoo/odoo/commit/10eee18a047d35305dc46282e610e88936d81ffc#diff-7525de0c57e690342ed3108fc9dcc8c2

**Comment by max3903** [comment]
@rousseldenis Thank you.
