### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/rma#314]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate

- [x] product_warranty - By @stefan-tecnativa - #358
- [x] rma - By @pedrobaeza - #361
- [x] rma_delivery - By @sbejaoui - #424
- [x] rma_sale - By @pedrobaeza - #364
- [x] rma_sale_mrp - By @pedrobaeza - #365
- [ ] stock_production_lot_warranty - By @IgnaQubiq - #380
- [ ] website_rma

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list

**Comment by imarulbala** [comment]
Migration to version 16.0

- product_warranty https://github.com/OCA/rma/pull/323
