### ISSUE TITLE
Migration to version 9.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/rma#54]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0
# Modules to migrate
- [ ] crm_rma_advance_location
- [x] crm_claim_rma - @cyrilgdn #86 
- [ ] crm_rma_lot_mass_return
- [ ] crm_claim_ext
- [ ] crm_rma_by_shop
- [x] product_warranty - Assigned to @cyrilgdn - #81
- [x] crm_rma_location - Assigned to @cyrilgdn - #82
- [ ] crm_rma_stock_location - Assigned to @cyrilgdn - #87
- [ ] crm_claim_categ_as_name
- [ ] crm_claim_rma_code - @cyrilgdn #85

**Comment by mdietrichc2c** [comment]
For information, our team is starting to migrate `crm_claim_rma`, `crm_rma_stock_location`, `crm_claim_rma` and `product_warranty` (as well as `crm_claim_code` and `crm_claim_type` in the OCA/crm branch).

**Comment by pedrobaeza** [comment]
Cool, I assigned you in the issue.

**Comment by cyrilgdn** [comment]
PR for product_warranty: #81

**Comment by cyrilgdn** [comment]
PR for crm_claim_rma_code: #85

**Comment by yvaucher** [comment]
@cyrilgdn Thanks I added your PR

**Comment by cyrilgdn** [comment]
PR for crm_claim_rma: #86

**Comment by cyrilgdn** [comment]
PR for crm_rma_stock_location: https://github.com/OCA/rma/pull/87/

**Comment by nhomar** [comment]
Nice.

Pllease this are base modules for a lot of things on our end, if you will change functionally some approach document properly.

Regards.
